//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCard3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.ThumberUpNumber = 0;
            this.CommentThumberUp = new HashSet<CommentThumberUp>();
        }
    
        public int Id { get; set; }
        public string Opinion { get; set; }
        public int ArticleId { get; set; }
        public int PersonId { get; set; }
        public int ThumberUpNumber { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentThumberUp> CommentThumberUp { get; set; }
    }
}
