//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCard3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyCardContainer : DbContext
    {
        public MyCardContainer()
            : base("name=MyCardContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Article> ArticleSet { get; set; }
        public virtual DbSet<Board> BoardSet { get; set; }
        public virtual DbSet<Comment> CommentSet { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<ArticleThumberUp> ArticleThumberUpSet { get; set; }
    }
}
