//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int Id { get; set; }
        public int A_ID { get; set; }
        public int B_ID { get; set; }
        public Nullable<bool> A_OK { get; set; }
        public Nullable<bool> B_OK { get; set; }
    }
}
